exclude:
  - '**/base.scss'
  - '**/grid.scss'
  - '**/gridlex-vars.scss'
  - '**/normalize.scss'
  - '**/AudioBoom.scss'
  - '**/ScoreBoardWidget.scss'
  - '**/icon-fonts.scss'
  - '**/*.css'
  - '**/node_modules/**/*.scss'
  - 'node_modules/**/*.scss'
  - 'ats-common-libs/**/*.scss'

severity: error

linters:

  BorderZero:
    enabled: true
    convention: zero

  BemDepth:
    enabled: true

  DeclarationOrder:
    enabled: false

  ExtendDirective:
    enabled: true

  ImportantRule: # set following team discussion
    enabled: false

  Indentation: # this section has been added to match .editorconfig settings
    enabled: true
    allow_non_nested_indentation: false
    character: tab
    width: 1

  LeadingZero:
    enabled: false

  NameFormat:
    enabled: true

  PrivateNamingConvention:
    enabled: true
    prefix: _

  PropertySortOrder:
    enabled: false

  QualifyingElement:
    enabled: false

  SelectorFormat:
    enabled: true
    convention: hyphenated_BEM
    class_convention: ^(?!js-).*
    class_convention_explanation: should not be written in the form js-*

  SingleLinePerProperty:
    enabled: true
    allow_single_line_rule_sets: false

  StringQuotes:
    enabled: true
    style: double_quotes
